---
title: "US Personal Consumption Expendictures Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(shiny)
library(leaflet)
library(ggridges)
library(sf)
library(tidycensus)
library(osmdata)
library(tigris)
library(ggthemes)
library(leaflegend)
library(knitr)

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = FALSE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)

```

```{r extract_specific data}
file_dir  <- "./data/SAGDP"
data_files <- list.files(file_dir)
file_paths <- str_c(file_dir, data_files) 

t1_file_list <- list.files(file_dir, pattern = "SAGDP2N")
t1_file_list <- t1_file_list[!str_detect(t1_file_list, c("AREAS", "definition", "Footnotes" , "modify"))]

personal_consumption.df <- tibble(
           file_dir   = "./data/SAGDP/", 
           file_list  = t1_file_list, 
           state      = map(str_split(string = file_list, "_"), 2),
           file_paths = str_c(file_dir, file_list)) %>%
  dplyr::select(state, file_paths)

personal_consumption_data <- personal_consumption.df %>%
  mutate( 
    data = map(.x = file_paths, ~read_csv(.x, show_col_types = FALSE, na = c("(L)","(D)","(NA)")))) %>%
  dplyr::select(-file_paths) %>%
  unnest() %>%
  filter(!LineCode %in% NA,
         !GeoName %in% 'United States *',
         !Description %in% c("All industry total","Private industries")) %>%
  select(!c(`1997`:`2009`) & !c(`2021`) & !c(`Unit`))

```


```{r data_read, include = FALSE}

consumption_percent_change <- personal_consumption_data %>%
  filter(!(GeoName %in% c("Southeast","Far West","Mideast","Great Lakes","Southeast","Plains","Rocky Mountain","New England","Puerto Rico", "Southwest", "District of Columbia"))) %>%
  group_by(state, GeoName) %>%
  summarise(across(`2010`:`2020`, ~ sum(.x, na.rm = TRUE))) %>%
  group_by(state, GeoName) %>%
   transmute(
    `2020` = ((`2020` - `2018`)/`2018`)*100,
     `2019` = ((`2019` - `2018`)/`2018`)*100,
     `2017` = ((`2017` - `2018`)/`2018`)*100,
     `2016` = ((`2016` - `2018`)/`2018`)*100,
     `2015` = ((`2015` - `2018`)/`2018`)*100,
     `2014` = ((`2014` - `2018`)/`2018`)*100,
     `2013` = ((`2013` - `2018`)/`2018`)*100,
     `2012` = ((`2012` - `2018`)/`2018`)*100,
     `2011` = ((`2010` - `2018`)/`2018`)*100,
     `2010` = ((`2018` - `2018`)/`2018`)*100,) %>%
  pivot_longer(cols = starts_with("20"), 
names_to = "change_year",
values_to = "percent_change") %>%
  mutate(percent_change = round(percent_change ,digit = 2) )

geo_states <- map_data("state") %>% mutate(region = str_to_title(region))

##for state boundary
geo_percent_change.df <- left_join(
  geo_states,
  consumption_percent_change,
  by = c( "region" = "GeoName") ) %>%
  select(!c("order","subregion")) %>%
  rename("Percent Change" = percent_change)

center_state_names <- data.frame(region = state.name, uni_long = state.center$x, uni_lat = state.center$y)

##for the value show on state 
consumption_map.df <- geo_percent_change.df %>% 
  select(!c("long","lat")) %>%
  left_join(
  center_state_names,
  geo_percent_change.df,
  by = c( "region" = "region") ) %>%
  select(c("state","change_year","Percent Change","uni_long","uni_lat")) %>% 
  unique() %>%
  mutate( text_label = str_c(state, 
                       "\n", `Percent Change`))


Number_description <- personal_consumption_data %>%
  filter(!(GeoName %in% c("Southeast","Far West","Mideast","Great Lakes","Southeast","Plains","Rocky Mountain","New England","Puerto Rico"))) %>%
  group_by(Description) %>%
  summarise(across(`2010`:`2020`, ~ sum(.x, na.rm = TRUE))) %>%
  pivot_longer(cols = starts_with("20"), 
names_to = "year",
values_to = "consumption") %>%
  separate(Description, into = c("Description", "details"), sep = " ") %>%
  select(!details)
```


```{r input_choices, echo = FALSE}
year_choices <- geo_percent_change.df %>%
  distinct(change_year) %>%
  pull() %>%
  na.omit()

consumption_range <- Number_description %>% 
  pull(consumption) %>%
  unique() %>%
  range(na.rm = TRUE)

year_choices_list <- Number_description %>%
  distinct(year) %>%
  pull() %>%
  na.omit()


```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r ui, echo = FALSE}


selectInput(
  inputId  = "change_year",
  label    = h2("Year for Total Consumption"),
  choices  = year_choices,
  selected = year_choices[1] 
)

sliderInput(
  inputId = "consumption",
  label   = h2("Consumption Amount"),
  min     = consumption_range[1],
  max     = consumption_range[2],
  value   = c(3000000, 10000000), 
  ticks   = FALSE
)

selectInput(
  inputId  = "year",
  label    = h2("Year for Personal Consumption by Industry"),
  choices  = year_choices_list,
  selected = year_choices_list[11] 
)

```
Column {data-width=600}
----------------------------------------------------------------------- 
```{r input_filter, echo = FALSE}
dataFilter <- reactive({

consumption_map.df %>%
  filter(
  change_year %in% input[["change_year"]] )
})

map_filter <- reactive({

geo_percent_change.df %>%
  filter(
  change_year %in% input[["change_year"]] )
})

number_D_dataFilter <- reactive({

Number_description %>%
  filter(
  consumption > input[["consumption"]][1],
  consumption < input[["consumption"]][2],
  year %in% input[["year"]],
  )
})
```

```{r}

renderPlotly({
 
  consumption_map.df  <- dataFilter()
  geo_percent_change.df <- map_filter()


percent_gg <- ggplot(geo_percent_change.df, aes(long, lat)) + 
  geom_polygon(aes(group = group, fill = `Percent Change`)) + 
  geom_text(data = consumption_map.df, aes(uni_long, uni_lat, label = text_label) ) +
 labs(
      x = "Longitude",
      y = "Latitude",
      title = "Total Consumption Percentage Change (%) for Different States Compared with 2018"
    ) +
   scale_fill_gradient(low='white', high='Orange')+
   theme_void()
  

ggplotly(percent_gg, tooltip ="label") %>% style(hoverinfo = "skip")
})

```

```{r n_description}
renderPlotly({
  #Call reactive filtered data
  Number_description  <- number_D_dataFilter()
  consumption_amount <- Number_description$consumption 
  
  #Render plot
Number_description  %>%
    mutate(
   Description = fct_reorder(Description, as.numeric(consumption), .desc = FALSE)
  ) %>%
  plot_ly(
    y = ~Description,
    x = ~consumption,
    marker = list(color = ~Description),
    name = ~Description,
    type   = "bar",
    colors = viridis::viridis_pal(option = "C")(consumption_amount) 
  ) %>%
  layout(
    title  = "Consumption amount by Industry Category",
    xaxis  = list(title = "Consumption Amount"),
    yaxis  = list(title = "Industry")
  )
})
```

